//import { index } from "./index.js";
let text = `If you are poor, no matter how bright you are, you cannot afford to work an internship for poverty wages or no wages at all. It is time to recognize that work is work and every worker must receive a living wage. #NationalInternDay Under our current dysfunctional health care system, even people with private health insurance get stuck with unpayable bills.

Under Medicare for All, there will be no unexpected bills, no copayments, no deductibles and no premiums. https://t.co/BBpDscFQ3t The United States is the only major country in the world that makes sick people check to see if their hospital or doctor is "in-network" before getting care.

Under Medicare for All you will be able to see any doctor and go to any hospital you want. https://t.co/9Bqc0lBSf0 The beauty of a Medicare for all system is its simplicity.

If your child is sick, you do not have to worry about out-of-network cost or copayments for them to see a pediatrician — they will get the care they need, free at the point of service. https://t.co/tFIjF0zD64 The 99: @briebriejoy and @YongJungC talk Organizing and how to join this movement. Watch to the end for a special guest... https://t.co/XfhodNdNWY No one should be saddled with a $300,000 bill because they had a child.

Under Medicare for All, there will be no copayments, deductibles or premiums. https://t.co/3zzw9FveA2 After months of protests led by immigrant communities, and allies from all over the country, the former internment compound at Fort Sill will NOT be used as a child detention center.

When we stand together, we win. We are not going to let Trump dehumanize our neighbors. https://t.co/Z559J9XbfZ Once we transition to Medicare for All you will never have to switch insurance providers ever again. And you will never get stuck with a copayment you can't afford. https://t.co/dvRdGF8vnz Have you been stuck with a huge medical bill? Share your story with Bernie during his health care town hall happening now. https://t.co/HsJz6CXW7A Kids cannot learn if they are hungry, and kids in the richest country on the planet should not be going hungry.

When I am president we are going to provide year-round, free, universal school meals. When elected president, I will NOT appoint an Education Secretary anything like Betsy DeVos.

Here's a radical idea: maybe we appoint someone who knows something about public education. Bernie gives a major education speech to educators at @UTLAnow Leadership Conference in Los Angeles https://t.co/ez8FANkqWk 9 years ago, 1.2 million gallons of crude oil spilled from Enbridge's 6B pipeline into the Kalamazoo River.

Today, with the climate crisis worsening, we must #ShutDownLine5 pipeline in Michigan and ban all new fossil fuel infrastructure. What we need is a Green New Deal. When the people stand together and fight back, we win. https://t.co/e2jKVa3Hsx 

I am pleased to announce the House has passed our budget deal 284-149. Great for our Military and our Vets. A big thank you! Give A$AP Rocky his FREEDOM. We do so much for Sweden but it doesn’t seem to work the other way around. Sweden should focus on its real crime problem! #FreeRocky Very disappointed in Prime Minister Stefan Löfven for being unable to act. Sweden has let our African American Community down in the United States. I watched the tapes of A$AP Rocky, and he was being followed and harassed by troublemakers. Treat Americans fairly! #FreeRocky ...What took place was completely unacceptable, and will not be tolerated. Bill de Blasio should act immediately! We love our Law Enforcement Officers all around this great Country. What took place in NYC with water being tossed on NYPD officers was a total disgrace. It is time for @NYCMayor @BilldeBlasio to STAND UP for those who protect our lives and serve us all so well... Beautiful Welcome Ceremony at the Pentagon this morning for our new Secretary of Defense, Mark @EsperDoD! https://t.co/qYDkjmqnOd House Republicans should support the TWO YEAR BUDGET AGREEMENT which greatly helps our Military and our Vets. I am totally with you! Mark Levin on @foxandfriends now! Great guy. Mark Levin will be on @foxandfriends now! Great guy. President Trump’s Approval Rating on Economy is at 52%, a 4 point jump. Fox Poll @foxandfriends  Shouldn’t this be at 100%? Best stock market, economy and unemployment numbers ever! Most people working within U.S. ever! Low interest rates, very low inflation! Country doing great! Fox Poll say best Economy in DECADES! ...impeachment, you have a Party of one. It’s over.” @kilmeade  “Nancy said, Jerry, please sit down. Very bad idea. We discovered that after putting so much time &amp; energy into the Mueller Report, it turns out Mueller didn’t know what was in his Report.” @SteveDoocy @foxandfriends `;

export default text; 
